version: "3.9"
services:
  node-http:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          ignore:
            - .git/
            - node_modules/
        - action: rebuild
          path: package.json
